/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import static GUI.CariKereta.Jam;
import static GUI.CariKereta.NamaKereta;
import static GUI.CariKereta.Rute;
import static GUI.CariKereta.Tanggal;
import Koneksi.KoneksiDB;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1CFont;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CetakTiket extends javax.swing.JFrame {

    /**
     * Creates new form CetakTiket
     */
    public CetakTiket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomor_tiket = new javax.swing.JTextField();
        lihat = new javax.swing.JButton();
        cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CETAK TIKET MANDIRI");

        jLabel2.setText("Nomor Tiket");

        lihat.setText("Lihat");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });

        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kereta", "Rute", "Tanggal", "Jam"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Keluar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nomor_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(lihat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cetak)
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomor_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihat)
                    .addComponent(cetak))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        // TODO add your handling code here:
        int IdTiket = Integer.parseInt(nomor_tiket.getText());
        try{
            Connection kon = KoneksiDB.getKoneksi();
            Statement stat = kon.createStatement();
            
            String sqlCari = "SELECT * FROM kereta INNER JOIN tiket ON tiket.nama_kereta = kereta.nama_kereta INNER JOIN rute ON tiket.id_rute = rute.id_rute INNER JOIN membeli ON tiket.id_tiket = membeli.id_tiket INNER JOIN penumpang ON membeli.nik = penumpang.nik WHERE tiket.id_tiket = \"+IdTiket+";
            ResultSet rs = stat.executeQuery(sqlCari);
            
            while(rs.next()){
                String nama = rs.getString("penumpang.nama");
                String kereta = rs.getString("kereta.nama_kereta");
                String berangkat = rs.getString("rute.berangkat");
                String tujuan = rs.getString("rute.tujuan");
                String tanggal = rs.getString("tiket.waktu").substring(0,10);
                String jam = rs.getString("tiket.waktu").substring(11,15);
             
                String rute = berangkat +"."+tujuan;
                
                DefaultTableModel model = (DefaultTableModel)tabel.getModel();
                
                Object []  dataYangDitampil = {nama, kereta, rute, tanggal, jam};
                model.addRow(dataYangDitampil);
                                
                }
            rs.close();
            stat.close();
            
        } catch (SQLException e) {
            String pesan = "Terjadi Lesalahan Dalam Menampilkan Tiket";
            JOptionPane.showMessageDialog(null, pesan + e.getMessage());
        }
    }//GEN-LAST:event_lihatActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        CetakTiketPDF();
    }//GEN-LAST:event_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CetakTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CetakTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CetakTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CetakTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CetakTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lihat;
    private javax.swing.JTextField nomor_tiket;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    private void CetakTiketPDF() {
//private void CetakTiketPDF(String Nama, String NamaKereta, String Rute, String Tanggal, String Jam) {
        PDPage TiketKA = new PDPage();
        
  ///   PDFont JenisFont = PDFont.COURIER;
        int FontSize = 12;
        
        try (PDDocument dokumen = new PDDocument()) {
            dokumen.addPage(TiketKA);
            
            PDPageContentStream content = new PDPageContentStream(dokumen, TiketKA);
            
            content.beginText();
//          content.setFont(JenisFont, TOP_ALIGNMENT);
            content.setLeading(20f);
            content.newLineAtOffset(50, 750);
            content.showText("TIKET KERETA API");
            content.newLine();
            content.newLine();
            String Nama = null;
            content.showText("NAMA PENUMPANG : " +Nama);
            content.newLine();
            content.showText("NAMA KERETA : " +NamaKereta);
            content.newLine();
            content.showText("NAMA RUTE : " +Rute);
            content.newLine();
            content.showText("TANGGAL : " +Tanggal);
            content.newLine();
            content.showText("JAM : " +Jam+"WIB");
            
            content.endText();
            dokumen.save("D:\\Kuliah\\SEMESTER 4\\Pemrograman Berorientasi Objek Lanjut Praktik/TiketKeretaApi-001.pdf");
            
            
        } catch (Exception e) {
            System.out.println("Gagal Membuat PDF");
        }
        try{
            File file = new File("D:\\Kuliah\\SEMESTER 4\\Pemrograman Berorientasi Objek Lanjut Praktik/TiketKeretaApi-001.pdf");
            if (file.exists()) {
                Desktop.getDesktop().open(file);
            } else{
                System.out.println("FILE TIDAK TERSEDIA => " +file.getAbsolutePath());
            }
            
        } catch (Exception e) {
                System.out.println("Gagal Membuka File PDF");

        }
    }
    
}
